site_name: SharpPluginLoader Documentation
site_url: https://fexty12573.github.io/SharpPluginLoader/

repo_name: Fexty12573/SharpPluginLoader
repo_url: https://github.com/Fexty12573/SharpPluginLoader/

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.inlinehilite
  - pymdownx.highlight
  - pymdownx.superfences

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.path
    - navigation.indexes
    - toc.follow
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
  language: en
  palette:
    - scheme: default
      toggle:
        icon: material/weather-sunny
        name: Default
      primary: slate blue
      accent: sky blue
    - scheme: slate
      toggle:
        icon: material/weather-night
        name: Slate
      primary: slate blue
      accent: sky blue

nav:
  - Home: index.md
  - Installation: Installation.md
  - Plugin Development:
    - Development/index.md
    - Getting Started: Development/GettingStarted.md
    - Game Objects: Development/GameObjects.md
    - Function Hooking: Development/FunctionHooking.md
    - Calling Native Functions: Development/CallingNativeFuncs.md
    - Rendering with ImGui: Development/ImGui.md
    - Rendering: Development/Rendering.md
  - API Reference:
    - API/index.md
  - Examples:
    - Examples/index.md
    - API Examples:
      - Direct Memory Access: Examples/API/DirectMemoryAccess.md
      - Logging: Examples/API/Logging.md
      - User Input: Examples/API/UserInput.md
    - Plugin Examples:
      - Quest End Skip: Examples/Plugins/QuestEndSkip.md
