on:
  pull-request:
    branches:
      - master
  push:
    branches:
      - docfx
      - master

permissions:
  actions: read
  pages: write
  id-token: write

concurrency:
  group: "docs"
  cancel-in-progress: false

jobs:
  publish-docs:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: .NET Setup
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.x
      
      - run: dotnet tool install -g docfx
      - run: docfx docs/docfx.json

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - if: steps.extract_branch.outputs.branch == 'master'
        name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          path: docs/_site
      - if: steps.extract_branch.outputs.branch == 'master'
        name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4